# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-30 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20160630_0512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Wine',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='wine',
            new_name='car',
        ),
    ]
